### ISSUE TITLE
Can't start acquisition

### ISSUE THREAD

**Issue by Korbinian89** [BogdanDIA/gr-dvbt#17]
Hey, thanks for sharing your work. I started with generating the demofiles (test -> testBB, testBB -> testout) and everything worked fine. But now i want to watch real DVB-T. There's just one problem, the ofdm_sym_acquisition restarts all the time (combined with "O"verruns). I use a DVB-T dongle with the RTL-SDR Source, not the UHD-Source. My Samplingrate is 2.5Ms/s, so i did some interpolation to get to 64/7Ms/s. Is the interpolation the problem why the acquisition restarts all the time? (2-3 times per second) My values for sym-acquisiton: FFT = 8k, Occupied Tones=6817, CP=2k (guard intervall is 1/4) and snr = 40. And another question, why do you multiply with 552.4µ? 
Thanks in advance.

**Comment by anthonynacz** [comment]
@Korbinian89  Sorry for such a late post , did you solve your issue and how ?
