### ISSUE TITLE
dvbt_tx example error

### ISSUE THREAD

**Issue by fpgasdr** [BogdanDIA/gr-dvbt#32]
hello,

I'm new to this tool and I just tried the dvbt_tx_8k example and got this error: 

Using Volk machine: avx2_64_mmx_orc
python: /build/gnuradio-bJXzXK/gnuradio-3.7.9.1/gr-dtv/lib/dvbt/dvbt_inner_coder_impl.cc:164: gr::dtv::dvbt_inner_coder_impl::dvbt_inner_coder_impl(int, int, gr::dtv::dvb_constellation_t, gr::dtv::dvbt_hierarchy_t, gr::dtv::dvb_code_rate_t): assertion `d_ninput % 1' failed. 

any ideas?.

**Comment by sirno-baka** [comment]
Same problem

**Comment by fpgasdr** [comment]
this problem is related with the gr-dtv code provided with gnuradio but not this repository.
